name: Build with ESP-IDF v5.4

on:
  push:
    branches: [ main, develop ]
    tags: '**' # Trigger on tags for releases
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Arduino build ESP32
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v5.4
        target: esp32
        command: "idf.py set-target esp32 && idf.py build"
    
    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        prerelease: true
        files: build/PSP-Bluetooth-Dongle.bin

